version: '3'
services:
  influxdb:
    image: influxdb:1.8
    ports:
      - "8086:8086"
    volumes:
      - influxdb:/var/lib/influxdb

  chronograf:
    image: chronograf
    ports:
      - "8888:8888"
    environment:
      - INFLUXDB_URL=http://influxdb:8086

  telegraf:
    image: telegraf
    volumes:
      - ./telegraf.conf:/etc/telegraf/telegraf.conf:ro

  kapacitor:
    image: kapacitor
    ports:
      - "9092:9092"
    volumes:
      - ./kapacitor.conf:/etc/kapacitor/kapacitor.conf:ro

volumes:
  influxdb:
